-- ============================================================
-- Отдел Образования Ачхой-Мартановского Района — ONLINE V22 — ЧИСТАЯ УСТАНОВКА
-- Выполнить целиком в Supabase Dashboard -> SQL Editor -> New query
-- Скрипт можно запускать повторно: он старается не дублировать данные.
-- ============================================================

begin;

create extension if not exists pgcrypto;

-- ---------- Справочники ----------
create table if not exists public.departments (
  id text primary key,
  name text not null,
  short_name text,
  email text unique,
  head_name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schools (
  id text primary key,
  name text not null,
  locality text,
  director_name text,
  responsible_name text,
  email text,
  rating numeric(5,2),
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null default 'Пользователь',
  role text not null default 'pending' check (role in ('chief','deputy','department_head','specialist','school_director','school_staff','observer','pending')),
  department_id text references public.departments(id) on delete set null,
  school_id text references public.schools(id) on delete set null,
  active boolean not null default true,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_lower_idx on public.profiles(lower(email));

create table if not exists public.user_invitations (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  full_name text,
  role text not null check (role in ('chief','deputy','department_head','specialist','school_director','school_staff','observer')),
  department_id text references public.departments(id) on delete cascade,
  school_id text references public.schools(id) on delete cascade,
  invited_by uuid references public.profiles(id) on delete set null,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  unique (email)
);
create unique index if not exists user_invitations_email_lower_idx on public.user_invitations(lower(email));

-- ---------- Поручения ----------
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  task_number text,
  title text not null,
  description text,
  department_id text not null references public.departments(id),
  direction text,
  creator_id uuid references public.profiles(id),
  creator_name text,
  status text not null default 'draft' check (status in ('draft','pending_approval','active','review','overdue','done','cancelled')),
  priority text not null default 'Обычное',
  deadline timestamptz not null,
  response_type text,
  requires_director boolean not null default true,
  approval_route text,
  weight numeric(4,2) not null default 1,
  repeat_rule text,
  recipients_mode text not null default 'all',
  form_schema jsonb not null default '{"fields":[]}'::jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.task_recipients (
  task_id bigint not null references public.tasks(id) on delete cascade,
  school_id text not null references public.schools(id) on delete cascade,
  status text not null default 'new' check (status in ('new','working','director','review','returned','accepted','overdue')),
  opened_at timestamptz,
  accepted_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (task_id, school_id)
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  task_id bigint not null references public.tasks(id) on delete cascade,
  school_id text not null references public.schools(id) on delete cascade,
  status text not null default 'draft' check (status in ('draft','director','review','returned','accepted')),
  current_version integer not null default 1,
  answers jsonb not null default '{}'::jsonb,
  field_files jsonb not null default '{}'::jsonb,
  comment text,
  director_comment text,
  reviewer_comment text,
  created_by uuid references public.profiles(id),
  reviewed_by uuid references public.profiles(id),
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (task_id, school_id)
);

create table if not exists public.submission_versions (
  id uuid primary key default gen_random_uuid(),
  submission_id uuid not null references public.submissions(id) on delete cascade,
  version integer not null,
  status text not null,
  answers jsonb not null default '{}'::jsonb,
  field_files jsonb not null default '{}'::jsonb,
  comment text,
  director_comment text,
  reviewer_comment text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  unique (submission_id, version)
);

create table if not exists public.task_comments (
  id uuid primary key default gen_random_uuid(),
  task_id bigint not null references public.tasks(id) on delete cascade,
  school_id text references public.schools(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  visibility text not null default 'school' check (visibility in ('school','all','internal')),
  body text not null,
  created_at timestamptz not null default now()
);

-- ---------- Файлы ----------
create table if not exists public.files (
  id uuid primary key default gen_random_uuid(),
  task_id bigint references public.tasks(id) on delete cascade,
  submission_id uuid references public.submissions(id) on delete cascade,
  uploader_id uuid not null references public.profiles(id) on delete cascade,
  school_id text references public.schools(id) on delete cascade,
  department_id text references public.departments(id) on delete cascade,
  bucket text not null default 'roo-documents',
  path text not null unique,
  file_name text not null,
  mime_type text,
  size_bytes bigint,
  field_label text,
  created_at timestamptz not null default now()
);

-- ---------- Экзамены ----------
create table if not exists public.exam_imports (
  id uuid primary key default gen_random_uuid(),
  academic_year text not null,
  exam_type text not null check (exam_type in ('ЕГЭ','ОГЭ','ГИА')),
  subject text,
  period text,
  school_id text references public.schools(id) on delete set null,
  source_file text,
  imported_rows integer not null default 0,
  errors_count integer not null default 0,
  uploaded_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.exam_results (
  id uuid primary key default gen_random_uuid(),
  import_id uuid references public.exam_imports(id) on delete cascade,
  source_row_id text unique,
  academic_year text not null,
  exam_type text not null check (exam_type in ('ЕГЭ','ОГЭ','ГИА')),
  period text,
  school_id text not null references public.schools(id) on delete cascade,
  student_name text not null,
  class_name text,
  subject text not null,
  score numeric(6,2),
  grade integer check (grade between 2 and 5),
  result_status text not null default 'Сдал',
  scheduled_time time,
  arrival_time time,
  late_minutes integer not null default 0,
  passed boolean,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists exam_results_filter_idx on public.exam_results(academic_year, exam_type, subject, school_id);
create index if not exists exam_results_student_idx on public.exam_results(student_name);

-- ---------- Система ----------
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_name text,
  action text not null,
  entity_type text not null default 'system',
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.design_settings (
  id integer primary key default 1 check (id = 1),
  settings jsonb not null default '{}'::jsonb,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.design_settings(id, settings) values (1, '{}'::jsonb) on conflict (id) do nothing;

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text,
  entity_type text,
  entity_id text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

-- ---------- Общие триггеры ----------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$ begin
  if not exists (select 1 from pg_trigger where tgname='departments_set_updated_at') then
    create trigger departments_set_updated_at before update on public.departments for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname='schools_set_updated_at') then
    create trigger schools_set_updated_at before update on public.schools for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname='profiles_set_updated_at') then
    create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname='tasks_set_updated_at') then
    create trigger tasks_set_updated_at before update on public.tasks for each row execute function public.set_updated_at();
  end if;
  if not exists (select 1 from pg_trigger where tgname='submissions_set_updated_at') then
    create trigger submissions_set_updated_at before update on public.submissions for each row execute function public.set_updated_at();
  end if;
end $$;

-- ---------- Определение роли пользователя ----------
create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$ select coalesce((select role from public.profiles where id = auth.uid() and active), 'pending') $$;

create or replace function public.current_department_id()
returns text
language sql
stable
security definer
set search_path = public
as $$ select department_id from public.profiles where id = auth.uid() and active $$;

create or replace function public.current_school_id()
returns text
language sql
stable
security definer
set search_path = public
as $$ select school_id from public.profiles where id = auth.uid() and active $$;

create or replace function public.is_management()
returns boolean
language sql
stable
security definer
set search_path = public
as $$ select public.current_role() in ('chief','deputy') $$;

create or replace function public.is_readonly_management()
returns boolean
language sql
stable
security definer
set search_path = public
as $$ select public.current_role() in ('chief','deputy','observer') $$;

create or replace function public.can_view_exam_data(target_school text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select case
    when public.current_role() in ('chief','deputy','observer') then true
    when public.current_role() in ('department_head','specialist')
      then public.current_department_id() in ('methodical','information')
    when public.current_role() in ('school_director','school_staff')
      then public.current_school_id() = target_school
    else false
  end
$$;

-- ---------- Создание профиля при регистрации ----------
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  invitation public.user_invitations%rowtype;
  assigned_role text := 'pending';
  assigned_department text := null;
  assigned_school text := null;
  assigned_name text := coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1));
  existing_profiles integer;
begin
  select * into invitation
  from public.user_invitations
  where lower(email)=lower(new.email) and used_at is null
  limit 1;

  select count(*) into existing_profiles from public.profiles where active;

  if invitation.id is not null then
    assigned_role := invitation.role;
    assigned_department := invitation.department_id;
    assigned_school := invitation.school_id;
    assigned_name := coalesce(invitation.full_name, assigned_name);
    update public.user_invitations set used_at=now() where id=invitation.id;
  elsif existing_profiles = 0 then
    -- Первый неизвестный аккаунт в пустой системе становится начальником РОО.
    -- Зарегистрируйте его сразу после выполнения SQL, до публикации ссылки.
    assigned_role := 'chief';
    assigned_name := coalesce(new.raw_user_meta_data->>'full_name','Начальник РОО');
  end if;

  insert into public.profiles(id,email,full_name,role,department_id,school_id,active,last_seen_at)
  values(new.id,new.email,assigned_name,assigned_role,assigned_department,assigned_school,assigned_role<>'pending',now())
  on conflict(id) do nothing;

  return new;
end;
$$;

do $$ begin
  if not exists (select 1 from pg_trigger where tgname='on_auth_user_created_roo') then
    create trigger on_auth_user_created_roo
      after insert on auth.users
      for each row execute function public.handle_new_auth_user();
  end if;
end $$;

-- ---------- Синхронизация статуса поручения школы ----------
create or replace function public.sync_recipient_from_submission()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.task_recipients(task_id,school_id,status,opened_at,accepted_at,completed_at,updated_at)
  values(
    new.task_id,
    new.school_id,
    new.status,
    coalesce((select opened_at from public.task_recipients where task_id=new.task_id and school_id=new.school_id), now()),
    case when new.status in ('draft','director','review','returned','accepted') then coalesce((select accepted_at from public.task_recipients where task_id=new.task_id and school_id=new.school_id), now()) else null end,
    case when new.status='accepted' then now() else null end,
    now()
  )
  on conflict(task_id,school_id) do update set
    status=excluded.status,
    completed_at=case when excluded.status='accepted' then now() else public.task_recipients.completed_at end,
    updated_at=now();
  return new;
end;
$$;

do $$ begin
  if not exists (select 1 from pg_trigger where tgname='submission_sync_recipient') then
    create trigger submission_sync_recipient after insert or update on public.submissions
      for each row execute function public.sync_recipient_from_submission();
  end if;
end $$;

-- ---------- Рейтинг отделов ----------
create or replace view public.department_performance with (security_invoker=true) as
with task_stats as (
  select department_id,
    count(*) as tasks_given,
    count(*) filter (where status='done') as completed,
    count(*) filter (where status='overdue') as overdue
  from public.tasks where status <> 'draft' group by department_id
), submission_stats as (
  select t.department_id,
    count(s.id) as responses,
    count(s.id) filter (where s.status='review') as waiting_review,
    count(s.id) filter (where s.status='returned') as returned_count,
    avg(extract(epoch from (s.updated_at-s.submitted_at))/3600.0)
      filter (where s.submitted_at is not null and s.status in ('accepted','returned')) as avg_review_hours
  from public.tasks t join public.submissions s on s.task_id=t.id group by t.department_id
)
select d.id,d.name,d.email,d.head_name,
  coalesce(ts.tasks_given,0) as tasks_given,
  coalesce(ts.completed,0) as completed,
  coalesce(ts.overdue,0) as overdue,
  coalesce(ss.waiting_review,0) as waiting_review,
  coalesce(ss.responses,0) as responses,
  case when ss.avg_review_hours is null then null else round(ss.avg_review_hours::numeric,1) end as avg_review_hours,
  case when coalesce(ts.completed,0)+coalesce(ts.overdue,0)+coalesce(ss.responses,0)=0 then null
    else round(greatest(0,least(100,
      100-coalesce(ts.overdue,0)*8-coalesce(ss.waiting_review,0)*2-coalesce(ss.returned_count,0)*2-greatest(coalesce(ss.avg_review_hours,0)-24,0)*0.5
    ))::numeric,1)
  end as rating
from public.departments d
left join task_stats ts on ts.department_id=d.id
left join submission_stats ss on ss.department_id=d.id;

create or replace view public.exam_school_summary with (security_invoker=true) as
select
  academic_year, exam_type, subject, school_id,
  count(*) as total,
  count(*) filter (where result_status='Не явился') as absent,
  count(*) filter (where passed is true) as passed,
  count(*) filter (where passed is false and result_status<>'Не явился') as failed,
  round(avg(score) filter (where score is not null),2) as average_score,
  max(score) as max_score,
  min(score) filter (where score is not null) as min_score,
  count(*) filter (where grade=5) as grade_5,
  count(*) filter (where grade=4) as grade_4,
  count(*) filter (where grade=3) as grade_3,
  count(*) filter (where grade=2) as grade_2,
  count(*) filter (where late_minutes>0) as late_count
from public.exam_results
group by academic_year,exam_type,subject,school_id;

-- ---------- RLS ----------
alter table public.departments enable row level security;
alter table public.schools enable row level security;
alter table public.profiles enable row level security;
alter table public.user_invitations enable row level security;
alter table public.tasks enable row level security;
alter table public.task_recipients enable row level security;
alter table public.submissions enable row level security;
alter table public.submission_versions enable row level security;
alter table public.task_comments enable row level security;
alter table public.files enable row level security;
alter table public.exam_imports enable row level security;
alter table public.exam_results enable row level security;
alter table public.audit_log enable row level security;
alter table public.design_settings enable row level security;
alter table public.notifications enable row level security;

-- Удаляем политики с теми же именами, чтобы скрипт можно было повторить.
do $$
declare r record;
begin
  for r in select schemaname,tablename,policyname from pg_policies where schemaname='public' and policyname like 'roo_%'
  loop execute format('drop policy if exists %I on %I.%I',r.policyname,r.schemaname,r.tablename); end loop;
end $$;

create policy roo_departments_select on public.departments for select to authenticated using (true);
create policy roo_departments_manage on public.departments for all to authenticated using (public.is_management()) with check (public.is_management());

create policy roo_schools_select on public.schools for select to authenticated using (true);
create policy roo_schools_manage on public.schools for all to authenticated using (public.is_management()) with check (public.is_management());

create policy roo_profiles_select on public.profiles for select to authenticated using (
  id=auth.uid()
  or public.current_role() in ('chief','deputy','observer')
  or (public.current_role()='department_head' and department_id=public.current_department_id())
  or (public.current_role()='school_director' and school_id=public.current_school_id())
);
create policy roo_profiles_management_update on public.profiles for update to authenticated using (public.is_management()) with check (public.is_management());

create policy roo_invites_select on public.user_invitations for select to authenticated using (public.is_management());
create policy roo_invites_insert on public.user_invitations for insert to authenticated with check (public.is_management());
create policy roo_invites_update on public.user_invitations for update to authenticated using (public.is_management()) with check (public.is_management());
create policy roo_invites_delete on public.user_invitations for delete to authenticated using (public.current_role()='chief');

create policy roo_tasks_select on public.tasks for select to authenticated using (
  public.current_role() in ('chief','deputy','observer')
  or (public.current_role() in ('department_head','specialist') and department_id=public.current_department_id())
  or exists(select 1 from public.task_recipients tr where tr.task_id=tasks.id and tr.school_id=public.current_school_id())
);
create policy roo_tasks_insert on public.tasks for insert to authenticated with check (
  public.current_role() in ('chief','deputy')
  or (public.current_role() in ('department_head','specialist') and department_id=public.current_department_id())
);
create policy roo_tasks_update on public.tasks for update to authenticated using (
  public.current_role() in ('chief','deputy')
  or (public.current_role()='department_head' and department_id=public.current_department_id())
  or (public.current_role()='specialist' and creator_id=auth.uid() and status='draft')
) with check (
  public.current_role() in ('chief','deputy')
  or (public.current_role()='department_head' and department_id=public.current_department_id())
  or (public.current_role()='specialist' and creator_id=auth.uid())
);
create policy roo_tasks_delete on public.tasks for delete to authenticated using (public.current_role()='chief');

create policy roo_recipients_select on public.task_recipients for select to authenticated using (
  public.current_role() in ('chief','deputy','observer')
  or school_id=public.current_school_id()
  or exists(select 1 from public.tasks t where t.id=task_recipients.task_id and t.department_id=public.current_department_id() and public.current_role() in ('department_head','specialist'))
);
create policy roo_recipients_manage on public.task_recipients for all to authenticated using (
  public.current_role() in ('chief','deputy')
  or exists(select 1 from public.tasks t where t.id=task_recipients.task_id and t.department_id=public.current_department_id() and public.current_role() in ('department_head','specialist'))
) with check (
  public.current_role() in ('chief','deputy')
  or exists(select 1 from public.tasks t where t.id=task_recipients.task_id and t.department_id=public.current_department_id() and public.current_role() in ('department_head','specialist'))
);

create policy roo_submissions_select on public.submissions for select to authenticated using (
  public.current_role() in ('chief','deputy','observer')
  or school_id=public.current_school_id()
  or exists(select 1 from public.tasks t where t.id=submissions.task_id and t.department_id=public.current_department_id() and public.current_role() in ('department_head','specialist'))
);
create policy roo_submissions_insert on public.submissions for insert to authenticated with check (
  (public.current_role()='school_staff' and school_id=public.current_school_id() and status in ('draft','director','returned'))
  or (public.current_role()='school_director' and school_id=public.current_school_id() and status in ('director','review','returned'))
  or public.current_role() in ('chief','deputy')
);
create policy roo_submissions_update_school_staff on public.submissions for update to authenticated using (
  public.current_role()='school_staff' and school_id=public.current_school_id()
) with check (
  public.current_role()='school_staff' and school_id=public.current_school_id() and status in ('draft','director','returned')
);
create policy roo_submissions_update_school_director on public.submissions for update to authenticated using (
  public.current_role()='school_director' and school_id=public.current_school_id()
) with check (
  public.current_role()='school_director' and school_id=public.current_school_id() and status in ('director','review','returned')
);
create policy roo_submissions_update_roo on public.submissions for update to authenticated using (
  public.current_role() in ('chief','deputy')
  or exists(select 1 from public.tasks t where t.id=submissions.task_id and t.department_id=public.current_department_id() and public.current_role() in ('department_head','specialist'))
) with check (
  public.current_role() in ('chief','deputy')
  or exists(select 1 from public.tasks t where t.id=submissions.task_id and t.department_id=public.current_department_id() and public.current_role() in ('department_head','specialist'))
);

create policy roo_versions_select on public.submission_versions for select to authenticated using (
  exists(select 1 from public.submissions s where s.id=submission_versions.submission_id and (
    public.current_role() in ('chief','deputy','observer')
    or s.school_id=public.current_school_id()
    or exists(select 1 from public.tasks t where t.id=s.task_id and t.department_id=public.current_department_id() and public.current_role() in ('department_head','specialist'))
  ))
);
create policy roo_versions_insert on public.submission_versions for insert to authenticated with check (
  exists(select 1 from public.submissions s where s.id=submission_versions.submission_id and (
    s.school_id=public.current_school_id()
    or public.current_role() in ('chief','deputy')
    or exists(select 1 from public.tasks t where t.id=s.task_id and t.department_id=public.current_department_id() and public.current_role() in ('department_head','specialist'))
  ))
);

create policy roo_comments_select on public.task_comments for select to authenticated using (
  public.current_role() in ('chief','deputy','observer')
  or author_id=auth.uid()
  or school_id=public.current_school_id()
  or exists(select 1 from public.tasks t where t.id=task_comments.task_id and t.department_id=public.current_department_id() and public.current_role() in ('department_head','specialist'))
);
create policy roo_comments_insert on public.task_comments for insert to authenticated with check (author_id=auth.uid());

create policy roo_files_select on public.files for select to authenticated using (
  uploader_id=auth.uid()
  or public.current_role() in ('chief','deputy','observer')
  or school_id=public.current_school_id()
  or department_id=public.current_department_id()
);
create policy roo_files_insert on public.files for insert to authenticated with check (uploader_id=auth.uid());
create policy roo_files_delete on public.files for delete to authenticated using (uploader_id=auth.uid() or public.current_role()='chief');

create policy roo_exam_imports_select on public.exam_imports for select to authenticated using (
  public.can_view_exam_data(coalesce(school_id,public.current_school_id()))
);
create policy roo_exam_imports_insert on public.exam_imports for insert to authenticated with check (
  public.current_role() in ('chief','deputy')
  or (public.current_role() in ('department_head','specialist') and public.current_department_id() in ('methodical','information'))
);
create policy roo_exam_imports_update on public.exam_imports for update to authenticated using (
  public.current_role() in ('chief','deputy')
  or (public.current_role()='department_head' and public.current_department_id() in ('methodical','information'))
) with check (true);
create policy roo_exam_imports_delete on public.exam_imports for delete to authenticated using (
  public.current_role() in ('chief','deputy')
  or (public.current_role()='department_head' and public.current_department_id() in ('methodical','information'))
);
create policy roo_exam_results_select on public.exam_results for select to authenticated using (public.can_view_exam_data(school_id));
create policy roo_exam_results_insert on public.exam_results for insert to authenticated with check (
  public.current_role() in ('chief','deputy')
  or (public.current_role() in ('department_head','specialist') and public.current_department_id() in ('methodical','information'))
);
create policy roo_exam_results_update on public.exam_results for update to authenticated using (
  public.current_role() in ('chief','deputy')
  or (public.current_role() in ('department_head','specialist') and public.current_department_id() in ('methodical','information'))
) with check (true);
create policy roo_exam_results_delete on public.exam_results for delete to authenticated using (
  public.current_role() in ('chief','deputy')
  or (public.current_role()='department_head' and public.current_department_id() in ('methodical','information'))
);

create policy roo_audit_select on public.audit_log for select to authenticated using (
  public.current_role() in ('chief','deputy','observer') or actor_id=auth.uid()
);
create policy roo_audit_insert on public.audit_log for insert to authenticated with check (actor_id=auth.uid());

create policy roo_design_select on public.design_settings for select to authenticated using (true);
create policy roo_design_update on public.design_settings for update to authenticated using (public.current_role() in ('chief','deputy')) with check (public.current_role() in ('chief','deputy'));
create policy roo_design_insert on public.design_settings for insert to authenticated with check (public.current_role() in ('chief','deputy') and id=1);

create policy roo_notifications_select on public.notifications for select to authenticated using (user_id=auth.uid());
create policy roo_notifications_update on public.notifications for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

-- Права Data API
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select on public.department_performance, public.exam_school_summary to authenticated;

-- ---------- Storage ----------
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values(
  'roo-documents','roo-documents',false,15728640,
  array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv','image/jpeg','image/png','image/webp','application/octet-stream']
)
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

do $$
declare r record;
begin
  for r in select policyname from pg_policies where schemaname='storage' and tablename='objects' and policyname like 'roo_storage_%'
  loop execute format('drop policy if exists %I on storage.objects',r.policyname); end loop;
end $$;

create policy roo_storage_insert on storage.objects for insert to authenticated
with check (
  bucket_id='roo-documents'
  and (storage.foldername(name))[1]='user'
  and (storage.foldername(name))[2]=auth.uid()::text
);
create policy roo_storage_select on storage.objects for select to authenticated
using (
  bucket_id='roo-documents'
  and (
    owner_id=auth.uid()::text
    or exists(select 1 from public.files f where f.path=storage.objects.name and (
      f.uploader_id=auth.uid()
      or public.current_role() in ('chief','deputy','observer')
      or f.school_id=public.current_school_id()
      or f.department_id=public.current_department_id()
    ))
  )
);
create policy roo_storage_delete on storage.objects for delete to authenticated
using (bucket_id='roo-documents' and (owner_id=auth.uid()::text or public.current_role()='chief'));

-- ---------- Realtime (если таблицы ещё не добавлены) ----------
do $$
begin
  begin alter publication supabase_realtime add table public.tasks; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.task_recipients; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.submissions; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.exam_results; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.design_settings; exception when duplicate_object then null; end;
end $$;

-- ---------- Исходные подразделения ----------
insert into public.departments(id,name,short_name,email,head_name) values
('management','Руководство РОО','Руководство',null,null),
('upbringing','Отдел воспитательной работы','Воспитательная работа','ruo.ovdo@mail.ru',null),
('general','Общий отдел','Общий отдел','ruo.npo@mail.ru',null),
('methodical','Методический отдел','Методический отдел','infometod@bk.ru',null),
('resources','Хозяйственный отдел','Хозяйственный отдел','ruo.khg@mail.ru',null),
('information','Информационный отдел','Информационный отдел','roo.inform@mail.ru',null)
on conflict(id) do update set name=excluded.name,short_name=excluded.short_name,email=excluded.email;

-- Предварительно разрешённые аккаунты начальников отделов.
insert into public.user_invitations(email,full_name,role,department_id) values
('ruo.ovdo@mail.ru','Начальник отдела воспитательной работы','department_head','upbringing'),
('ruo.npo@mail.ru','Начальник общего отдела','department_head','general'),
('infometod@bk.ru','Начальник методического отдела','department_head','methodical'),
('ruo.khg@mail.ru','Начальник хозяйственного отдела','department_head','resources'),
('roo.inform@mail.ru','Начальник информационного отдела','department_head','information')
on conflict(email) do update set role=excluded.role,department_id=excluded.department_id;

-- Школы не создаются автоматически. Добавьте их в интерфейсе или при импорте Excel.

commit;

-- После успешного выполнения:
-- 1) Откройте сайт ONLINE V22 — ЧИСТАЯ УСТАНОВКА.
-- 2) Нажмите «Первый вход / создать пароль» и зарегистрируйте СВОЮ почту первой.
-- 3) Первый неизвестный аккаунт станет Начальником РОО.
-- 4) После этого начальники отделов регистрируются по пяти заранее разрешённым почтам.
